spring:
  application:
    name: puppynote
  datasource:
    url: jdbc:mysql://localhost:3306/puppynote?useSSL=true
    username: root
    password: 'test123'
  jpa:
    open-in-view: false

server:
  port: 8080